

export default {
  "meta": {},
  "id": "_default",
  "module": () => import('../src/pages/_module.svelte'),
  "file": {
    "path": "src/pages/_module.svelte",
    "dir": "src/pages",
    "base": "_module.svelte",
    "ext": ".svelte",
    "name": "_module"
  },
  "rootName": "default",
  "routifyDir": import.meta.url,
  "children": [
    {
      "meta": {
        "order": 1
      },
      "id": "_default_1_home",
      "name": "home",
      "module": false,
      "file": {
        "path": "src/pages/1.home",
        "dir": "src/pages",
        "base": "1.home",
        "ext": ".home",
        "name": "1.home"
      },
      "children": [
        {
          "meta": {},
          "id": "_default_1_home_index_svelte",
          "name": "index",
          "module": () => import('../src/pages/1.home/index.svelte'),
          "file": {
            "path": "src/pages/1.home/index.svelte",
            "dir": "src/pages/1.home",
            "base": "index.svelte",
            "ext": ".svelte",
            "name": "index"
          },
          "children": []
        }
      ]
    },
    {
      "meta": {
        "repos": [
          {
            "data": {
              "id": 210910840,
              "node_id": "MDEwOlJlcG9zaXRvcnkyMTA5MTA4NDA=",
              "name": "routify",
              "full_name": "roxiness/routify",
              "private": false,
              "owner": {
                "login": "roxiness",
                "id": 58428864,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjU4NDI4ODY0",
                "avatar_url": "https://avatars.githubusercontent.com/u/58428864?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/roxiness",
                "html_url": "https://github.com/roxiness",
                "followers_url": "https://api.github.com/users/roxiness/followers",
                "following_url": "https://api.github.com/users/roxiness/following{/other_user}",
                "gists_url": "https://api.github.com/users/roxiness/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/roxiness/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/roxiness/subscriptions",
                "organizations_url": "https://api.github.com/users/roxiness/orgs",
                "repos_url": "https://api.github.com/users/roxiness/repos",
                "events_url": "https://api.github.com/users/roxiness/events{/privacy}",
                "received_events_url": "https://api.github.com/users/roxiness/received_events",
                "type": "Organization",
                "site_admin": false
              },
              "html_url": "https://github.com/roxiness/routify",
              "description": "Automated Svelte routes",
              "fork": false,
              "url": "https://api.github.com/repos/roxiness/routify",
              "forks_url": "https://api.github.com/repos/roxiness/routify/forks",
              "keys_url": "https://api.github.com/repos/roxiness/routify/keys{/key_id}",
              "collaborators_url": "https://api.github.com/repos/roxiness/routify/collaborators{/collaborator}",
              "teams_url": "https://api.github.com/repos/roxiness/routify/teams",
              "hooks_url": "https://api.github.com/repos/roxiness/routify/hooks",
              "issue_events_url": "https://api.github.com/repos/roxiness/routify/issues/events{/number}",
              "events_url": "https://api.github.com/repos/roxiness/routify/events",
              "assignees_url": "https://api.github.com/repos/roxiness/routify/assignees{/user}",
              "branches_url": "https://api.github.com/repos/roxiness/routify/branches{/branch}",
              "tags_url": "https://api.github.com/repos/roxiness/routify/tags",
              "blobs_url": "https://api.github.com/repos/roxiness/routify/git/blobs{/sha}",
              "git_tags_url": "https://api.github.com/repos/roxiness/routify/git/tags{/sha}",
              "git_refs_url": "https://api.github.com/repos/roxiness/routify/git/refs{/sha}",
              "trees_url": "https://api.github.com/repos/roxiness/routify/git/trees{/sha}",
              "statuses_url": "https://api.github.com/repos/roxiness/routify/statuses/{sha}",
              "languages_url": "https://api.github.com/repos/roxiness/routify/languages",
              "stargazers_url": "https://api.github.com/repos/roxiness/routify/stargazers",
              "contributors_url": "https://api.github.com/repos/roxiness/routify/contributors",
              "subscribers_url": "https://api.github.com/repos/roxiness/routify/subscribers",
              "subscription_url": "https://api.github.com/repos/roxiness/routify/subscription",
              "commits_url": "https://api.github.com/repos/roxiness/routify/commits{/sha}",
              "git_commits_url": "https://api.github.com/repos/roxiness/routify/git/commits{/sha}",
              "comments_url": "https://api.github.com/repos/roxiness/routify/comments{/number}",
              "issue_comment_url": "https://api.github.com/repos/roxiness/routify/issues/comments{/number}",
              "contents_url": "https://api.github.com/repos/roxiness/routify/contents/{+path}",
              "compare_url": "https://api.github.com/repos/roxiness/routify/compare/{base}...{head}",
              "merges_url": "https://api.github.com/repos/roxiness/routify/merges",
              "archive_url": "https://api.github.com/repos/roxiness/routify/{archive_format}{/ref}",
              "downloads_url": "https://api.github.com/repos/roxiness/routify/downloads",
              "issues_url": "https://api.github.com/repos/roxiness/routify/issues{/number}",
              "pulls_url": "https://api.github.com/repos/roxiness/routify/pulls{/number}",
              "milestones_url": "https://api.github.com/repos/roxiness/routify/milestones{/number}",
              "notifications_url": "https://api.github.com/repos/roxiness/routify/notifications{?since,all,participating}",
              "labels_url": "https://api.github.com/repos/roxiness/routify/labels{/name}",
              "releases_url": "https://api.github.com/repos/roxiness/routify/releases{/id}",
              "deployments_url": "https://api.github.com/repos/roxiness/routify/deployments",
              "created_at": "2019-09-25T18:13:42Z",
              "updated_at": "2022-01-28T02:56:51Z",
              "pushed_at": "2022-01-27T18:07:42Z",
              "git_url": "git://github.com/roxiness/routify.git",
              "ssh_url": "git@github.com:roxiness/routify.git",
              "clone_url": "https://github.com/roxiness/routify.git",
              "svn_url": "https://github.com/roxiness/routify",
              "homepage": "https://routify.dev",
              "size": 6050,
              "stargazers_count": 1439,
              "watchers_count": 1439,
              "language": "JavaScript",
              "has_issues": true,
              "has_projects": true,
              "has_downloads": true,
              "has_wiki": true,
              "has_pages": false,
              "forks_count": 62,
              "mirror_url": null,
              "archived": false,
              "disabled": false,
              "open_issues_count": 24,
              "license": {
                "key": "mit",
                "name": "MIT License",
                "spdx_id": "MIT",
                "url": "https://api.github.com/licenses/mit",
                "node_id": "MDc6TGljZW5zZTEz"
              },
              "allow_forking": true,
              "is_template": false,
              "topics": [],
              "visibility": "public",
              "forks": 62,
              "open_issues": 24,
              "watchers": 1439,
              "default_branch": "master",
              "temp_clone_token": null,
              "organization": {
                "login": "roxiness",
                "id": 58428864,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjU4NDI4ODY0",
                "avatar_url": "https://avatars.githubusercontent.com/u/58428864?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/roxiness",
                "html_url": "https://github.com/roxiness",
                "followers_url": "https://api.github.com/users/roxiness/followers",
                "following_url": "https://api.github.com/users/roxiness/following{/other_user}",
                "gists_url": "https://api.github.com/users/roxiness/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/roxiness/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/roxiness/subscriptions",
                "organizations_url": "https://api.github.com/users/roxiness/orgs",
                "repos_url": "https://api.github.com/users/roxiness/repos",
                "events_url": "https://api.github.com/users/roxiness/events{/privacy}",
                "received_events_url": "https://api.github.com/users/roxiness/received_events",
                "type": "Organization",
                "site_admin": false
              },
              "network_count": 62,
              "subscribers_count": 23
            },
            "readme": () => import('./cached/src/pages/2.projects/_module.svelte/split/div_align_center_n_i-2054--1ivb1p.js').then(r => r.default)
          },
          {
            "data": {
              "id": 299939642,
              "node_id": "MDEwOlJlcG9zaXRvcnkyOTk5Mzk2NDI=",
              "name": "configent",
              "full_name": "roxiness/configent",
              "private": false,
              "owner": {
                "login": "roxiness",
                "id": 58428864,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjU4NDI4ODY0",
                "avatar_url": "https://avatars.githubusercontent.com/u/58428864?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/roxiness",
                "html_url": "https://github.com/roxiness",
                "followers_url": "https://api.github.com/users/roxiness/followers",
                "following_url": "https://api.github.com/users/roxiness/following{/other_user}",
                "gists_url": "https://api.github.com/users/roxiness/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/roxiness/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/roxiness/subscriptions",
                "organizations_url": "https://api.github.com/users/roxiness/orgs",
                "repos_url": "https://api.github.com/users/roxiness/repos",
                "events_url": "https://api.github.com/users/roxiness/events{/privacy}",
                "received_events_url": "https://api.github.com/users/roxiness/received_events",
                "type": "Organization",
                "site_admin": false
              },
              "html_url": "https://github.com/roxiness/configent",
              "description": "no fuzz configurator",
              "fork": false,
              "url": "https://api.github.com/repos/roxiness/configent",
              "forks_url": "https://api.github.com/repos/roxiness/configent/forks",
              "keys_url": "https://api.github.com/repos/roxiness/configent/keys{/key_id}",
              "collaborators_url": "https://api.github.com/repos/roxiness/configent/collaborators{/collaborator}",
              "teams_url": "https://api.github.com/repos/roxiness/configent/teams",
              "hooks_url": "https://api.github.com/repos/roxiness/configent/hooks",
              "issue_events_url": "https://api.github.com/repos/roxiness/configent/issues/events{/number}",
              "events_url": "https://api.github.com/repos/roxiness/configent/events",
              "assignees_url": "https://api.github.com/repos/roxiness/configent/assignees{/user}",
              "branches_url": "https://api.github.com/repos/roxiness/configent/branches{/branch}",
              "tags_url": "https://api.github.com/repos/roxiness/configent/tags",
              "blobs_url": "https://api.github.com/repos/roxiness/configent/git/blobs{/sha}",
              "git_tags_url": "https://api.github.com/repos/roxiness/configent/git/tags{/sha}",
              "git_refs_url": "https://api.github.com/repos/roxiness/configent/git/refs{/sha}",
              "trees_url": "https://api.github.com/repos/roxiness/configent/git/trees{/sha}",
              "statuses_url": "https://api.github.com/repos/roxiness/configent/statuses/{sha}",
              "languages_url": "https://api.github.com/repos/roxiness/configent/languages",
              "stargazers_url": "https://api.github.com/repos/roxiness/configent/stargazers",
              "contributors_url": "https://api.github.com/repos/roxiness/configent/contributors",
              "subscribers_url": "https://api.github.com/repos/roxiness/configent/subscribers",
              "subscription_url": "https://api.github.com/repos/roxiness/configent/subscription",
              "commits_url": "https://api.github.com/repos/roxiness/configent/commits{/sha}",
              "git_commits_url": "https://api.github.com/repos/roxiness/configent/git/commits{/sha}",
              "comments_url": "https://api.github.com/repos/roxiness/configent/comments{/number}",
              "issue_comment_url": "https://api.github.com/repos/roxiness/configent/issues/comments{/number}",
              "contents_url": "https://api.github.com/repos/roxiness/configent/contents/{+path}",
              "compare_url": "https://api.github.com/repos/roxiness/configent/compare/{base}...{head}",
              "merges_url": "https://api.github.com/repos/roxiness/configent/merges",
              "archive_url": "https://api.github.com/repos/roxiness/configent/{archive_format}{/ref}",
              "downloads_url": "https://api.github.com/repos/roxiness/configent/downloads",
              "issues_url": "https://api.github.com/repos/roxiness/configent/issues{/number}",
              "pulls_url": "https://api.github.com/repos/roxiness/configent/pulls{/number}",
              "milestones_url": "https://api.github.com/repos/roxiness/configent/milestones{/number}",
              "notifications_url": "https://api.github.com/repos/roxiness/configent/notifications{?since,all,participating}",
              "labels_url": "https://api.github.com/repos/roxiness/configent/labels{/name}",
              "releases_url": "https://api.github.com/repos/roxiness/configent/releases{/id}",
              "deployments_url": "https://api.github.com/repos/roxiness/configent/deployments",
              "created_at": "2020-09-30T14:06:51Z",
              "updated_at": "2021-08-06T00:46:02Z",
              "pushed_at": "2021-12-20T15:46:25Z",
              "git_url": "git://github.com/roxiness/configent.git",
              "ssh_url": "git@github.com:roxiness/configent.git",
              "clone_url": "https://github.com/roxiness/configent.git",
              "svn_url": "https://github.com/roxiness/configent",
              "homepage": null,
              "size": 536,
              "stargazers_count": 10,
              "watchers_count": 10,
              "language": "JavaScript",
              "has_issues": true,
              "has_projects": true,
              "has_downloads": true,
              "has_wiki": true,
              "has_pages": false,
              "forks_count": 1,
              "mirror_url": null,
              "archived": false,
              "disabled": false,
              "open_issues_count": 1,
              "license": null,
              "allow_forking": true,
              "is_template": false,
              "topics": [],
              "visibility": "public",
              "forks": 1,
              "open_issues": 1,
              "watchers": 10,
              "default_branch": "master",
              "temp_clone_token": null,
              "organization": {
                "login": "roxiness",
                "id": 58428864,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjU4NDI4ODY0",
                "avatar_url": "https://avatars.githubusercontent.com/u/58428864?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/roxiness",
                "html_url": "https://github.com/roxiness",
                "followers_url": "https://api.github.com/users/roxiness/followers",
                "following_url": "https://api.github.com/users/roxiness/following{/other_user}",
                "gists_url": "https://api.github.com/users/roxiness/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/roxiness/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/roxiness/subscriptions",
                "organizations_url": "https://api.github.com/users/roxiness/orgs",
                "repos_url": "https://api.github.com/users/roxiness/repos",
                "events_url": "https://api.github.com/users/roxiness/events{/privacy}",
                "received_events_url": "https://api.github.com/users/roxiness/received_events",
                "type": "Organization",
                "site_admin": false
              },
              "network_count": 1,
              "subscribers_count": 2
            },
            "readme": () => import('./cached/src/pages/2.projects/_module.svelte/split/div_align_center_n_i-6042-f6acgr.js').then(r => r.default)
          },
          {
            "data": {
              "id": 236830441,
              "node_id": "MDEwOlJlcG9zaXRvcnkyMzY4MzA0NDE=",
              "name": "tossr",
              "full_name": "roxiness/tossr",
              "private": false,
              "owner": {
                "login": "roxiness",
                "id": 58428864,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjU4NDI4ODY0",
                "avatar_url": "https://avatars.githubusercontent.com/u/58428864?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/roxiness",
                "html_url": "https://github.com/roxiness",
                "followers_url": "https://api.github.com/users/roxiness/followers",
                "following_url": "https://api.github.com/users/roxiness/following{/other_user}",
                "gists_url": "https://api.github.com/users/roxiness/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/roxiness/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/roxiness/subscriptions",
                "organizations_url": "https://api.github.com/users/roxiness/orgs",
                "repos_url": "https://api.github.com/users/roxiness/repos",
                "events_url": "https://api.github.com/users/roxiness/events{/privacy}",
                "received_events_url": "https://api.github.com/users/roxiness/received_events",
                "type": "Organization",
                "site_admin": false
              },
              "html_url": "https://github.com/roxiness/tossr",
              "description": "Universal SSR renderer powered by JSDOM",
              "fork": false,
              "url": "https://api.github.com/repos/roxiness/tossr",
              "forks_url": "https://api.github.com/repos/roxiness/tossr/forks",
              "keys_url": "https://api.github.com/repos/roxiness/tossr/keys{/key_id}",
              "collaborators_url": "https://api.github.com/repos/roxiness/tossr/collaborators{/collaborator}",
              "teams_url": "https://api.github.com/repos/roxiness/tossr/teams",
              "hooks_url": "https://api.github.com/repos/roxiness/tossr/hooks",
              "issue_events_url": "https://api.github.com/repos/roxiness/tossr/issues/events{/number}",
              "events_url": "https://api.github.com/repos/roxiness/tossr/events",
              "assignees_url": "https://api.github.com/repos/roxiness/tossr/assignees{/user}",
              "branches_url": "https://api.github.com/repos/roxiness/tossr/branches{/branch}",
              "tags_url": "https://api.github.com/repos/roxiness/tossr/tags",
              "blobs_url": "https://api.github.com/repos/roxiness/tossr/git/blobs{/sha}",
              "git_tags_url": "https://api.github.com/repos/roxiness/tossr/git/tags{/sha}",
              "git_refs_url": "https://api.github.com/repos/roxiness/tossr/git/refs{/sha}",
              "trees_url": "https://api.github.com/repos/roxiness/tossr/git/trees{/sha}",
              "statuses_url": "https://api.github.com/repos/roxiness/tossr/statuses/{sha}",
              "languages_url": "https://api.github.com/repos/roxiness/tossr/languages",
              "stargazers_url": "https://api.github.com/repos/roxiness/tossr/stargazers",
              "contributors_url": "https://api.github.com/repos/roxiness/tossr/contributors",
              "subscribers_url": "https://api.github.com/repos/roxiness/tossr/subscribers",
              "subscription_url": "https://api.github.com/repos/roxiness/tossr/subscription",
              "commits_url": "https://api.github.com/repos/roxiness/tossr/commits{/sha}",
              "git_commits_url": "https://api.github.com/repos/roxiness/tossr/git/commits{/sha}",
              "comments_url": "https://api.github.com/repos/roxiness/tossr/comments{/number}",
              "issue_comment_url": "https://api.github.com/repos/roxiness/tossr/issues/comments{/number}",
              "contents_url": "https://api.github.com/repos/roxiness/tossr/contents/{+path}",
              "compare_url": "https://api.github.com/repos/roxiness/tossr/compare/{base}...{head}",
              "merges_url": "https://api.github.com/repos/roxiness/tossr/merges",
              "archive_url": "https://api.github.com/repos/roxiness/tossr/{archive_format}{/ref}",
              "downloads_url": "https://api.github.com/repos/roxiness/tossr/downloads",
              "issues_url": "https://api.github.com/repos/roxiness/tossr/issues{/number}",
              "pulls_url": "https://api.github.com/repos/roxiness/tossr/pulls{/number}",
              "milestones_url": "https://api.github.com/repos/roxiness/tossr/milestones{/number}",
              "notifications_url": "https://api.github.com/repos/roxiness/tossr/notifications{?since,all,participating}",
              "labels_url": "https://api.github.com/repos/roxiness/tossr/labels{/name}",
              "releases_url": "https://api.github.com/repos/roxiness/tossr/releases{/id}",
              "deployments_url": "https://api.github.com/repos/roxiness/tossr/deployments",
              "created_at": "2020-01-28T20:08:35Z",
              "updated_at": "2021-12-29T03:02:43Z",
              "pushed_at": "2021-12-20T15:48:06Z",
              "git_url": "git://github.com/roxiness/tossr.git",
              "ssh_url": "git@github.com:roxiness/tossr.git",
              "clone_url": "https://github.com/roxiness/tossr.git",
              "svn_url": "https://github.com/roxiness/tossr",
              "homepage": "",
              "size": 203,
              "stargazers_count": 34,
              "watchers_count": 34,
              "language": "JavaScript",
              "has_issues": true,
              "has_projects": true,
              "has_downloads": true,
              "has_wiki": true,
              "has_pages": false,
              "forks_count": 6,
              "mirror_url": null,
              "archived": false,
              "disabled": false,
              "open_issues_count": 3,
              "license": null,
              "allow_forking": true,
              "is_template": false,
              "topics": [],
              "visibility": "public",
              "forks": 6,
              "open_issues": 3,
              "watchers": 34,
              "default_branch": "master",
              "temp_clone_token": null,
              "organization": {
                "login": "roxiness",
                "id": 58428864,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjU4NDI4ODY0",
                "avatar_url": "https://avatars.githubusercontent.com/u/58428864?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/roxiness",
                "html_url": "https://github.com/roxiness",
                "followers_url": "https://api.github.com/users/roxiness/followers",
                "following_url": "https://api.github.com/users/roxiness/following{/other_user}",
                "gists_url": "https://api.github.com/users/roxiness/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/roxiness/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/roxiness/subscriptions",
                "organizations_url": "https://api.github.com/users/roxiness/orgs",
                "repos_url": "https://api.github.com/users/roxiness/repos",
                "events_url": "https://api.github.com/users/roxiness/events{/privacy}",
                "received_events_url": "https://api.github.com/users/roxiness/received_events",
                "type": "Organization",
                "site_admin": false
              },
              "network_count": 6,
              "subscribers_count": 4
            },
            "readme": () => import('./cached/src/pages/2.projects/_module.svelte/split/div_align_center_n_i-4921--kzwpwn.js').then(r => r.default)
          },
          {
            "data": {
              "id": 324626484,
              "node_id": "MDEwOlJlcG9zaXRvcnkzMjQ2MjY0ODQ=",
              "name": "stackmix",
              "full_name": "roxiness/stackmix",
              "private": false,
              "owner": {
                "login": "roxiness",
                "id": 58428864,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjU4NDI4ODY0",
                "avatar_url": "https://avatars.githubusercontent.com/u/58428864?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/roxiness",
                "html_url": "https://github.com/roxiness",
                "followers_url": "https://api.github.com/users/roxiness/followers",
                "following_url": "https://api.github.com/users/roxiness/following{/other_user}",
                "gists_url": "https://api.github.com/users/roxiness/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/roxiness/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/roxiness/subscriptions",
                "organizations_url": "https://api.github.com/users/roxiness/orgs",
                "repos_url": "https://api.github.com/users/roxiness/repos",
                "events_url": "https://api.github.com/users/roxiness/events{/privacy}",
                "received_events_url": "https://api.github.com/users/roxiness/received_events",
                "type": "Organization",
                "site_admin": false
              },
              "html_url": "https://github.com/roxiness/stackmix",
              "description": "A collection of templates for Routify.",
              "fork": false,
              "url": "https://api.github.com/repos/roxiness/stackmix",
              "forks_url": "https://api.github.com/repos/roxiness/stackmix/forks",
              "keys_url": "https://api.github.com/repos/roxiness/stackmix/keys{/key_id}",
              "collaborators_url": "https://api.github.com/repos/roxiness/stackmix/collaborators{/collaborator}",
              "teams_url": "https://api.github.com/repos/roxiness/stackmix/teams",
              "hooks_url": "https://api.github.com/repos/roxiness/stackmix/hooks",
              "issue_events_url": "https://api.github.com/repos/roxiness/stackmix/issues/events{/number}",
              "events_url": "https://api.github.com/repos/roxiness/stackmix/events",
              "assignees_url": "https://api.github.com/repos/roxiness/stackmix/assignees{/user}",
              "branches_url": "https://api.github.com/repos/roxiness/stackmix/branches{/branch}",
              "tags_url": "https://api.github.com/repos/roxiness/stackmix/tags",
              "blobs_url": "https://api.github.com/repos/roxiness/stackmix/git/blobs{/sha}",
              "git_tags_url": "https://api.github.com/repos/roxiness/stackmix/git/tags{/sha}",
              "git_refs_url": "https://api.github.com/repos/roxiness/stackmix/git/refs{/sha}",
              "trees_url": "https://api.github.com/repos/roxiness/stackmix/git/trees{/sha}",
              "statuses_url": "https://api.github.com/repos/roxiness/stackmix/statuses/{sha}",
              "languages_url": "https://api.github.com/repos/roxiness/stackmix/languages",
              "stargazers_url": "https://api.github.com/repos/roxiness/stackmix/stargazers",
              "contributors_url": "https://api.github.com/repos/roxiness/stackmix/contributors",
              "subscribers_url": "https://api.github.com/repos/roxiness/stackmix/subscribers",
              "subscription_url": "https://api.github.com/repos/roxiness/stackmix/subscription",
              "commits_url": "https://api.github.com/repos/roxiness/stackmix/commits{/sha}",
              "git_commits_url": "https://api.github.com/repos/roxiness/stackmix/git/commits{/sha}",
              "comments_url": "https://api.github.com/repos/roxiness/stackmix/comments{/number}",
              "issue_comment_url": "https://api.github.com/repos/roxiness/stackmix/issues/comments{/number}",
              "contents_url": "https://api.github.com/repos/roxiness/stackmix/contents/{+path}",
              "compare_url": "https://api.github.com/repos/roxiness/stackmix/compare/{base}...{head}",
              "merges_url": "https://api.github.com/repos/roxiness/stackmix/merges",
              "archive_url": "https://api.github.com/repos/roxiness/stackmix/{archive_format}{/ref}",
              "downloads_url": "https://api.github.com/repos/roxiness/stackmix/downloads",
              "issues_url": "https://api.github.com/repos/roxiness/stackmix/issues{/number}",
              "pulls_url": "https://api.github.com/repos/roxiness/stackmix/pulls{/number}",
              "milestones_url": "https://api.github.com/repos/roxiness/stackmix/milestones{/number}",
              "notifications_url": "https://api.github.com/repos/roxiness/stackmix/notifications{?since,all,participating}",
              "labels_url": "https://api.github.com/repos/roxiness/stackmix/labels{/name}",
              "releases_url": "https://api.github.com/repos/roxiness/stackmix/releases{/id}",
              "deployments_url": "https://api.github.com/repos/roxiness/stackmix/deployments",
              "created_at": "2020-12-26T20:02:30Z",
              "updated_at": "2022-01-22T17:08:32Z",
              "pushed_at": "2021-12-26T18:55:25Z",
              "git_url": "git://github.com/roxiness/stackmix.git",
              "ssh_url": "git@github.com:roxiness/stackmix.git",
              "clone_url": "https://github.com/roxiness/stackmix.git",
              "svn_url": "https://github.com/roxiness/stackmix",
              "homepage": null,
              "size": 387,
              "stargazers_count": 22,
              "watchers_count": 22,
              "language": "JavaScript",
              "has_issues": true,
              "has_projects": true,
              "has_downloads": true,
              "has_wiki": true,
              "has_pages": false,
              "forks_count": 3,
              "mirror_url": null,
              "archived": false,
              "disabled": false,
              "open_issues_count": 4,
              "license": null,
              "allow_forking": true,
              "is_template": false,
              "topics": [],
              "visibility": "public",
              "forks": 3,
              "open_issues": 4,
              "watchers": 22,
              "default_branch": "master",
              "temp_clone_token": null,
              "organization": {
                "login": "roxiness",
                "id": 58428864,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjU4NDI4ODY0",
                "avatar_url": "https://avatars.githubusercontent.com/u/58428864?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/roxiness",
                "html_url": "https://github.com/roxiness",
                "followers_url": "https://api.github.com/users/roxiness/followers",
                "following_url": "https://api.github.com/users/roxiness/following{/other_user}",
                "gists_url": "https://api.github.com/users/roxiness/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/roxiness/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/roxiness/subscriptions",
                "organizations_url": "https://api.github.com/users/roxiness/orgs",
                "repos_url": "https://api.github.com/users/roxiness/repos",
                "events_url": "https://api.github.com/users/roxiness/events{/privacy}",
                "received_events_url": "https://api.github.com/users/roxiness/received_events",
                "type": "Organization",
                "site_admin": false
              },
              "network_count": 3,
              "subscribers_count": 7
            },
            "readme": () => import('./cached/src/pages/2.projects/_module.svelte/split/p_align_center_n_img-1382--j17q2v.js').then(r => r.default)
          },
          {
            "data": {
              "id": 314868584,
              "node_id": "MDEwOlJlcG9zaXRvcnkzMTQ4Njg1ODQ=",
              "name": "poindexter",
              "full_name": "roxiness/poindexter",
              "private": false,
              "owner": {
                "login": "roxiness",
                "id": 58428864,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjU4NDI4ODY0",
                "avatar_url": "https://avatars.githubusercontent.com/u/58428864?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/roxiness",
                "html_url": "https://github.com/roxiness",
                "followers_url": "https://api.github.com/users/roxiness/followers",
                "following_url": "https://api.github.com/users/roxiness/following{/other_user}",
                "gists_url": "https://api.github.com/users/roxiness/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/roxiness/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/roxiness/subscriptions",
                "organizations_url": "https://api.github.com/users/roxiness/orgs",
                "repos_url": "https://api.github.com/users/roxiness/repos",
                "events_url": "https://api.github.com/users/roxiness/events{/privacy}",
                "received_events_url": "https://api.github.com/users/roxiness/received_events",
                "type": "Organization",
                "site_admin": false
              },
              "html_url": "https://github.com/roxiness/poindexter",
              "description": "Search engine for your static site",
              "fork": false,
              "url": "https://api.github.com/repos/roxiness/poindexter",
              "forks_url": "https://api.github.com/repos/roxiness/poindexter/forks",
              "keys_url": "https://api.github.com/repos/roxiness/poindexter/keys{/key_id}",
              "collaborators_url": "https://api.github.com/repos/roxiness/poindexter/collaborators{/collaborator}",
              "teams_url": "https://api.github.com/repos/roxiness/poindexter/teams",
              "hooks_url": "https://api.github.com/repos/roxiness/poindexter/hooks",
              "issue_events_url": "https://api.github.com/repos/roxiness/poindexter/issues/events{/number}",
              "events_url": "https://api.github.com/repos/roxiness/poindexter/events",
              "assignees_url": "https://api.github.com/repos/roxiness/poindexter/assignees{/user}",
              "branches_url": "https://api.github.com/repos/roxiness/poindexter/branches{/branch}",
              "tags_url": "https://api.github.com/repos/roxiness/poindexter/tags",
              "blobs_url": "https://api.github.com/repos/roxiness/poindexter/git/blobs{/sha}",
              "git_tags_url": "https://api.github.com/repos/roxiness/poindexter/git/tags{/sha}",
              "git_refs_url": "https://api.github.com/repos/roxiness/poindexter/git/refs{/sha}",
              "trees_url": "https://api.github.com/repos/roxiness/poindexter/git/trees{/sha}",
              "statuses_url": "https://api.github.com/repos/roxiness/poindexter/statuses/{sha}",
              "languages_url": "https://api.github.com/repos/roxiness/poindexter/languages",
              "stargazers_url": "https://api.github.com/repos/roxiness/poindexter/stargazers",
              "contributors_url": "https://api.github.com/repos/roxiness/poindexter/contributors",
              "subscribers_url": "https://api.github.com/repos/roxiness/poindexter/subscribers",
              "subscription_url": "https://api.github.com/repos/roxiness/poindexter/subscription",
              "commits_url": "https://api.github.com/repos/roxiness/poindexter/commits{/sha}",
              "git_commits_url": "https://api.github.com/repos/roxiness/poindexter/git/commits{/sha}",
              "comments_url": "https://api.github.com/repos/roxiness/poindexter/comments{/number}",
              "issue_comment_url": "https://api.github.com/repos/roxiness/poindexter/issues/comments{/number}",
              "contents_url": "https://api.github.com/repos/roxiness/poindexter/contents/{+path}",
              "compare_url": "https://api.github.com/repos/roxiness/poindexter/compare/{base}...{head}",
              "merges_url": "https://api.github.com/repos/roxiness/poindexter/merges",
              "archive_url": "https://api.github.com/repos/roxiness/poindexter/{archive_format}{/ref}",
              "downloads_url": "https://api.github.com/repos/roxiness/poindexter/downloads",
              "issues_url": "https://api.github.com/repos/roxiness/poindexter/issues{/number}",
              "pulls_url": "https://api.github.com/repos/roxiness/poindexter/pulls{/number}",
              "milestones_url": "https://api.github.com/repos/roxiness/poindexter/milestones{/number}",
              "notifications_url": "https://api.github.com/repos/roxiness/poindexter/notifications{?since,all,participating}",
              "labels_url": "https://api.github.com/repos/roxiness/poindexter/labels{/name}",
              "releases_url": "https://api.github.com/repos/roxiness/poindexter/releases{/id}",
              "deployments_url": "https://api.github.com/repos/roxiness/poindexter/deployments",
              "created_at": "2020-11-21T17:41:49Z",
              "updated_at": "2022-01-24T18:37:20Z",
              "pushed_at": "2021-05-19T11:06:34Z",
              "git_url": "git://github.com/roxiness/poindexter.git",
              "ssh_url": "git@github.com:roxiness/poindexter.git",
              "clone_url": "https://github.com/roxiness/poindexter.git",
              "svn_url": "https://github.com/roxiness/poindexter",
              "homepage": "",
              "size": 647,
              "stargazers_count": 73,
              "watchers_count": 73,
              "language": "JavaScript",
              "has_issues": true,
              "has_projects": true,
              "has_downloads": true,
              "has_wiki": true,
              "has_pages": false,
              "forks_count": 2,
              "mirror_url": null,
              "archived": false,
              "disabled": false,
              "open_issues_count": 0,
              "license": null,
              "allow_forking": true,
              "is_template": false,
              "topics": [],
              "visibility": "public",
              "forks": 2,
              "open_issues": 0,
              "watchers": 73,
              "default_branch": "master",
              "temp_clone_token": null,
              "organization": {
                "login": "roxiness",
                "id": 58428864,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjU4NDI4ODY0",
                "avatar_url": "https://avatars.githubusercontent.com/u/58428864?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/roxiness",
                "html_url": "https://github.com/roxiness",
                "followers_url": "https://api.github.com/users/roxiness/followers",
                "following_url": "https://api.github.com/users/roxiness/following{/other_user}",
                "gists_url": "https://api.github.com/users/roxiness/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/roxiness/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/roxiness/subscriptions",
                "organizations_url": "https://api.github.com/users/roxiness/orgs",
                "repos_url": "https://api.github.com/users/roxiness/repos",
                "events_url": "https://api.github.com/users/roxiness/events{/privacy}",
                "received_events_url": "https://api.github.com/users/roxiness/received_events",
                "type": "Organization",
                "site_admin": false
              },
              "network_count": 2,
              "subscribers_count": 3
            },
            "readme": () => import('./cached/src/pages/2.projects/_module.svelte/split/div_align_center_n_i-3807--tsvbbz.js').then(r => r.default)
          },
          {
            "data": {
              "id": 407183730,
              "node_id": "MDEwOlJlcG9zaXRvcnk0MDcxODM3MzA=",
              "name": "consolite",
              "full_name": "jakobrosenberg/consolite",
              "private": false,
              "owner": {
                "login": "jakobrosenberg",
                "id": 4153004,
                "node_id": "MDQ6VXNlcjQxNTMwMDQ=",
                "avatar_url": "https://avatars.githubusercontent.com/u/4153004?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/jakobrosenberg",
                "html_url": "https://github.com/jakobrosenberg",
                "followers_url": "https://api.github.com/users/jakobrosenberg/followers",
                "following_url": "https://api.github.com/users/jakobrosenberg/following{/other_user}",
                "gists_url": "https://api.github.com/users/jakobrosenberg/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/jakobrosenberg/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/jakobrosenberg/subscriptions",
                "organizations_url": "https://api.github.com/users/jakobrosenberg/orgs",
                "repos_url": "https://api.github.com/users/jakobrosenberg/repos",
                "events_url": "https://api.github.com/users/jakobrosenberg/events{/privacy}",
                "received_events_url": "https://api.github.com/users/jakobrosenberg/received_events",
                "type": "User",
                "site_admin": false
              },
              "html_url": "https://github.com/jakobrosenberg/consolite",
              "description": "tiny logger that features line numbers, log levels, log prefixes and nesting",
              "fork": false,
              "url": "https://api.github.com/repos/jakobrosenberg/consolite",
              "forks_url": "https://api.github.com/repos/jakobrosenberg/consolite/forks",
              "keys_url": "https://api.github.com/repos/jakobrosenberg/consolite/keys{/key_id}",
              "collaborators_url": "https://api.github.com/repos/jakobrosenberg/consolite/collaborators{/collaborator}",
              "teams_url": "https://api.github.com/repos/jakobrosenberg/consolite/teams",
              "hooks_url": "https://api.github.com/repos/jakobrosenberg/consolite/hooks",
              "issue_events_url": "https://api.github.com/repos/jakobrosenberg/consolite/issues/events{/number}",
              "events_url": "https://api.github.com/repos/jakobrosenberg/consolite/events",
              "assignees_url": "https://api.github.com/repos/jakobrosenberg/consolite/assignees{/user}",
              "branches_url": "https://api.github.com/repos/jakobrosenberg/consolite/branches{/branch}",
              "tags_url": "https://api.github.com/repos/jakobrosenberg/consolite/tags",
              "blobs_url": "https://api.github.com/repos/jakobrosenberg/consolite/git/blobs{/sha}",
              "git_tags_url": "https://api.github.com/repos/jakobrosenberg/consolite/git/tags{/sha}",
              "git_refs_url": "https://api.github.com/repos/jakobrosenberg/consolite/git/refs{/sha}",
              "trees_url": "https://api.github.com/repos/jakobrosenberg/consolite/git/trees{/sha}",
              "statuses_url": "https://api.github.com/repos/jakobrosenberg/consolite/statuses/{sha}",
              "languages_url": "https://api.github.com/repos/jakobrosenberg/consolite/languages",
              "stargazers_url": "https://api.github.com/repos/jakobrosenberg/consolite/stargazers",
              "contributors_url": "https://api.github.com/repos/jakobrosenberg/consolite/contributors",
              "subscribers_url": "https://api.github.com/repos/jakobrosenberg/consolite/subscribers",
              "subscription_url": "https://api.github.com/repos/jakobrosenberg/consolite/subscription",
              "commits_url": "https://api.github.com/repos/jakobrosenberg/consolite/commits{/sha}",
              "git_commits_url": "https://api.github.com/repos/jakobrosenberg/consolite/git/commits{/sha}",
              "comments_url": "https://api.github.com/repos/jakobrosenberg/consolite/comments{/number}",
              "issue_comment_url": "https://api.github.com/repos/jakobrosenberg/consolite/issues/comments{/number}",
              "contents_url": "https://api.github.com/repos/jakobrosenberg/consolite/contents/{+path}",
              "compare_url": "https://api.github.com/repos/jakobrosenberg/consolite/compare/{base}...{head}",
              "merges_url": "https://api.github.com/repos/jakobrosenberg/consolite/merges",
              "archive_url": "https://api.github.com/repos/jakobrosenberg/consolite/{archive_format}{/ref}",
              "downloads_url": "https://api.github.com/repos/jakobrosenberg/consolite/downloads",
              "issues_url": "https://api.github.com/repos/jakobrosenberg/consolite/issues{/number}",
              "pulls_url": "https://api.github.com/repos/jakobrosenberg/consolite/pulls{/number}",
              "milestones_url": "https://api.github.com/repos/jakobrosenberg/consolite/milestones{/number}",
              "notifications_url": "https://api.github.com/repos/jakobrosenberg/consolite/notifications{?since,all,participating}",
              "labels_url": "https://api.github.com/repos/jakobrosenberg/consolite/labels{/name}",
              "releases_url": "https://api.github.com/repos/jakobrosenberg/consolite/releases{/id}",
              "deployments_url": "https://api.github.com/repos/jakobrosenberg/consolite/deployments",
              "created_at": "2021-09-16T13:52:08Z",
              "updated_at": "2022-01-07T11:12:48Z",
              "pushed_at": "2022-01-10T07:51:29Z",
              "git_url": "git://github.com/jakobrosenberg/consolite.git",
              "ssh_url": "git@github.com:jakobrosenberg/consolite.git",
              "clone_url": "https://github.com/jakobrosenberg/consolite.git",
              "svn_url": "https://github.com/jakobrosenberg/consolite",
              "homepage": null,
              "size": 236,
              "stargazers_count": 2,
              "watchers_count": 2,
              "language": "JavaScript",
              "has_issues": true,
              "has_projects": true,
              "has_downloads": true,
              "has_wiki": true,
              "has_pages": false,
              "forks_count": 1,
              "mirror_url": null,
              "archived": false,
              "disabled": false,
              "open_issues_count": 0,
              "license": null,
              "allow_forking": true,
              "is_template": false,
              "topics": [],
              "visibility": "public",
              "forks": 1,
              "open_issues": 0,
              "watchers": 2,
              "default_branch": "main",
              "temp_clone_token": null,
              "network_count": 1,
              "subscribers_count": 1
            },
            "readme": () => import('./cached/src/pages/2.projects/_module.svelte/split/img_src_https_github-2871--9idip6.js').then(r => r.default)
          }
        ],
        "order": 2
      },
      "id": "_default_2_projects",
      "name": "projects",
      "module": () => import('../src/pages/2.projects/_module.svelte'),
      "file": {
        "path": "src/pages/2.projects/_module.svelte",
        "dir": "src/pages/2.projects",
        "base": "_module.svelte",
        "ext": ".svelte",
        "name": "_module"
      },
      "children": [
        {
          "meta": {
            "dynamic": true
          },
          "id": "_default_2_projects__project__svelte",
          "name": "[project]",
          "module": () => import('../src/pages/2.projects/[project].svelte'),
          "file": {
            "path": "src/pages/2.projects/[project].svelte",
            "dir": "src/pages/2.projects",
            "base": "[project].svelte",
            "ext": ".svelte",
            "name": "[project]"
          },
          "children": []
        }
      ]
    },
    {
      "meta": {
        "title": "about me",
        "order": 3
      },
      "id": "_default_3_about_me",
      "name": "about-me",
      "module": () => import('../src/pages/3.about-me/_module.svelte'),
      "file": {
        "path": "src/pages/3.about-me/_module.svelte",
        "dir": "src/pages/3.about-me",
        "base": "_module.svelte",
        "ext": ".svelte",
        "name": "_module"
      },
      "children": [
        {
          "meta": {},
          "id": "_default_3_about_me_index_svelte",
          "name": "index",
          "module": () => import('../src/pages/3.about-me/index.svelte'),
          "file": {
            "path": "src/pages/3.about-me/index.svelte",
            "dir": "src/pages/3.about-me",
            "base": "index.svelte",
            "ext": ".svelte",
            "name": "index"
          },
          "children": []
        }
      ]
    },
    {
      "meta": {},
      "id": "_default__loader_svelte",
      "name": "_loader",
      "module": () => import('../src/pages/_loader.svelte'),
      "file": {
        "path": "src/pages/_loader.svelte",
        "dir": "src/pages",
        "base": "_loader.svelte",
        "ext": ".svelte",
        "name": "_loader"
      },
      "children": []
    },
    {
      "meta": {},
      "id": "_default__navigation_svelte",
      "name": "_navigation",
      "module": () => import('../src/pages/_navigation.svelte'),
      "file": {
        "path": "src/pages/_navigation.svelte",
        "dir": "src/pages",
        "base": "_navigation.svelte",
        "ext": ".svelte",
        "name": "_navigation"
      },
      "children": []
    },
    {
      "meta": {},
      "id": "_default_index_svelte",
      "name": "index",
      "module": () => import('../src/pages/index.svelte'),
      "file": {
        "path": "src/pages/index.svelte",
        "dir": "src/pages",
        "base": "index.svelte",
        "ext": ".svelte",
        "name": "index"
      },
      "children": []
    }
  ]
}